### ISSUE TITLE
Endless chain of unfound plugins for ESLint

### ISSUE THREAD

**Issue by v1adko** [kentcdodds/kcd-scripts#10]
- `kcd-scripts` version: 0.25.1
- `node` version: 8.6.0
- `npm` (or `yarn`) version: yarn 1.1.0
- `OS`: Mac OS Sierra (10.12.6)

**What you did**:
`yarn add -D kcd-scripts`
`yarn lint:js` -> `kcd-scripts lint`

**What happened**:

Basically a series of errors saying that some plugin or config is not found, after I run the lint command.

![screen shot 2017-10-13 at 7 41 01 pm](https://user-images.githubusercontent.com/11582927/31556466-dd4e53b2-b04d-11e7-92ca-75bbab3ef288.png)

**Problem description**:
I'm trying to move my existing project to use CRA for production build (codesplitting, etc.) and kcd-scripts for dev (linting, prettier, precommit) to avoid config bloat and hide all of the webpack + babel mess. CRA was no problem, but as I moved to dev workflow, trying to run kcd-scripts lint resulted in missing some sort of plugin or config. After doing `yarn add -D the_missing_thing` and repeating the lint command it spat out anther missing dep and so on. I've continued installing more and more of these and each time `kcd-scripts lint` took more and more time to run.
I'm currently on my 10th missing module and I don't think it should be this way :)
The whole point of the toolkits is to encapsulate dependencies and I get this:

![screen shot 2017-10-13 at 7 42 30 pm](https://user-images.githubusercontent.com/11582927/31556485-f019df16-b04d-11e7-80f7-39429dd85d64.png)

**Suggested solution**:
I think that `eslint`'s module-resolver is scanning all modules in node_modules and pulling their eslint-configs and then it throws when it doesn't find something. But I'm not sure, it's a wild guess based from the error and I'm pretty sure kcd-scripts does not need stuff like `cssnano` to run.
TBH I don't know why I even have that in my dependencies, but it's node - not surprising:)

Thank you for your work @kentcdodds, I really enjoy all of the OSS things you do.

**Comment by kentcdodds** [comment]
Hi @v1adko! I'm happy you're giving `kcd-scripts` a try :)

> I'm pretty sure kcd-scripts does not need stuff like cssnano to run.

You're correct. I'm not sure why it's trying to read that. My guess is that it's trying to lint files in `node_modules`. Could you try `kcd-scripts lint --debug`? The `--debug` flag will be forwarded to `eslint` and it'll show you what files it's trying to lint. If it is trying to lint those files, could you look into what it's using for the eslint ignore?

Actually, now that I think of it I remembered there's an existing issue! https://github.com/eslint/eslint/issues/9227

To solve this problem, I've always added an [`eslintIgnore` property to my `package.json`](https://github.com/paypal/downshift/blob/master/package.json#L76-L82). I'm hoping that we can solve this issue in ESLint eventually. Maybe I'll take some time to work on that because `paypal-scripts` will need this fixed as well. But feel free to work on that yourself!

I'm going to go ahead and close this as it's not actionable in this project but will be solved by eslint.

**Comment by v1adko** [comment]
Thank you, adding `eslintIgnore` did help (.eslintignore worked too), even though it required `eslint-plugin-babel` and `eslint-plugin-jest`, but stopped at those two. 

Is it possible to encapsulate those within kcd-scripts too?

Would be nice if we could pass something like [--ignore-path](https://eslint.org/docs/user-guide/configuring#using-an-alternate-file) to use .gitignore and not duplicate the ignore paths.

**Comment by kentcdodds** [comment]
Those should definitely be encapsulated within `kcd-scripts`. I've not had trouble with them. What version of npm are you using?

**Comment by v1adko** [comment]
I use yarn 1.1.0

**Comment by kentcdodds** [comment]
> Also would be nice if we could pass something like --ignore-path to use .gitignore and not duplicate the ignore paths.

[You can](https://github.com/kentcdodds/kcd-scripts/blob/master/src/scripts/lint.js#L22) :wink:

**Comment by kentcdodds** [comment]
I don't use yarn, so I don't plan on supporting that in `kcd-scripts`. But I'm happy to accept a pull request if it doesn't complicate the codebase too much.

**Comment by v1adko** [comment]
Of course I can :) Thanks.
OK, I'll try to figure it out. 

Interestingly after dropping node_modules and yarn.lock and installing again issue persists.
And funny enough, installing kcd-scripts as a dependency and not a dev dependency it requires only `eslint-plugin-jest`.

**Comment by kentcdodds** [comment]
Well that's totally weird. Sounds like it could be an issue with combining react-scripts and kcd-scripts. Though I haven't had this problem in [this project](https://github.com/kentcdodds/react-workshop/blob/master/package.json) 🤔

**Comment by kentcdodds** [comment]
Try `yarn why babel-plugin-jest` and `npm ls babel-plugin-jest`. That'll tell you what packages require those packages...

**Comment by v1adko** [comment]
> Thank you, I will. And I'll definitely try to make it work with yarn.
-- 
*    Sincerely,*


*Vlad Kolbaya**Software Developer*
+380999477880 <javascript:void(0);> / *+16506918523 <javascript:void(0);>*
<vlad.kolbaya@gmail.com>  <https://github.com/v1adko>
<http://linkedin.com/in/v1adko>  <http://www.facebook.com/v1adko>
<http://telegram.me/v1adko>
