### ISSUE TITLE
High-level visibility of configurations

### ISSUE THREAD

**Issue by rektide** [kentcdodds/kcd-scripts#155]
- `kcd-scripts` version: 6.2.3
- `node` version: 12.16.1
- `npm` (or `yarn`) version: 6.13.4

Relevant code or config

all the config produced by kcd-scripts

What you did:

i introduced kcd-scripts to our team in order to set up a clear repeateable process 

What happened:

we now have a consistent means of deploying configuration to our projects, but our team has a weak understanding of what rules we have subjected ourselves to.

Problem description:

trying to understand what eslint and what babel configuration we have is a bit complicated, as there are numerous different configurations that are combined (in eslints case) and a variety of conditionals in the babelrc config generator. eslint in particular has been hard to understand.

Suggested solution:

it would be lovely to have a way to preview the aggregated eslint rules, for example. i'm less sure what could be done about, for example, babel, but that's less difficult to understand.

**Comment by kentcdodds** [comment]
This project is open source, but I make no effort to make it easy for other people to use other than myself. So sorry, I don't have the bandwidth.

I recommend forking it and improving it in whatever way you wish.

**Comment by rektide** [comment]
For anyone who happens upon this, one can `eslint --print-config some/random/file.js` to get the js rules for that file. Thanks eslint discord for the help there.

Closing for now. Godspeed all.
