### ISSUE TITLE
babel-plugin-minify-dead-code-elimination removes function names

### ISSUE THREAD

**Issue by mpeyper** [kentcdodds/kcd-scripts#188]
- `kcd-scripts` version: 7.5.3
- `node` version: 12.20.0
- `npm` (or `yarn`) version: 6.14.8

Relevant code or config

```javascript
export function createFunc1() {
  function func() {
  }
  return func
}

export function createFunc2() {
  function func() {
  }
  const name = func.name // not returned, just used
  return func
}
```

What you did:

Run `kcd-scripts build`

What happened:

The output is

```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.createFunc1 = createFunc1;
exports.createFunc2 = createFunc2;

function createFunc1() {
  return function () {};
}

function createFunc2() {
  function func() {}

  func.name; // not returned, just used

  return func;
}
```

Reproduction repository:

[Babel REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAMwK4DsDGMCWEVzVYAQxmADFU0BGACgEo4BvAKDkQqxzfTsYF8mWcAjCRRcydAG4m_UJFhcM2XPiIly6AEw9mrCUs76d_QWhwBneCkIBbYHAC8igHTW7kuAHpPcFBHjCoijAACYANHAAVkiWcDGhAqyBYorSvEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact%2Ctypescript&prettier=true&targets=&version=7.12.12&externalPlugins=babel-plugin-minify-dead-code-elimination%400.5.1)

Problem description:

The name of the function returned in `createFunc1` gets removed thanks to `babel-plugin-minify-dead-code-elimination`.  This is causing me problems in a node package (specifically a testing library) where the name gets removed and consequently does not appear in stack traces which hurts debugability when things go wrong.

I can understand the desire to remove this when building for browsers (reduced bundle size), but I don't personally see many advantages to this for a node/test package.

Suggested solution:

There is an [option to keep function names in the plugin](https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-dead-code-elimination#options), so we could set that the be true and keep the rest of the functionality.  We could use the [`isTest` flag](https://github.com/kentcdodds/kcd-scripts/blob/2e7e31267d1fab9dcb4d9a0d3a589cb8b3726472/src/config/babelrc.js#L14) to conditionally set the option for tests only.

Similarly, we could use the `isTest` flag to remove the plugin all together for tests.

Either solution would suffice for my issue.  I'm also happy to submit the PR for this change if you agree with it and can advise me which approach is your preference.

**Comment by kentcdodds** [comment]
I'm happy with your suggestion of enabling that option during tests 👍
