### ISSUE TITLE
Support webpack build

### ISSUE THREAD

**Issue by AndersDJohnson** [kentcdodds/kcd-scripts#21]
Looks like you support a Rollup build. Would you also consider adding support for Webpack?

For extensibility, could take inspiration from https://github.com/timarney/react-app-rewired.

**Comment by kentcdodds** [comment]
paypal-scripts (the internal to paypal version of this project) has support for webpack-built applications. kcd-scripts however does not have that goal in mind. If I want to build an app with webpack, I'll just use react-scripts. In some cases I'll use them together and use react-scripts for the `start` and `build` scripts, and `kcd-scripts` for the rest.

Thanks for the issue @AndersDJohnson, but I'm going to close this one as out of scope.
