### ISSUE TITLE
Incorrect `latest` version tag in NPM

### ISSUE THREAD

**Issue by mpeyper** [kentcdodds/kcd-scripts#213]
- `kcd-scripts` version `10.1.1`/`11.0.0`:
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

Relevant code or config

```sh
npm i kcd-scripts@latest
```

What you did:

Tried installing the latest version after the release notes for `10.1.0` told me about the accidental breaking changes and the reversion.

What happened:

Version `10.1.1.` is installed instead of version `11.0.0`.

Reproduction repository:

N/A

Problem description:

I assume it's a mistake that `kcd-scripts@latest` is pointing to `10.1.1` in NPM, right? https://www.npmjs.com/package/kcd-scripts?activeTab=versions

Suggested solution:

Push the latest tag to `11.0.0`.

**Comment by kentcdodds** [comment]
Thanks! Sorry for my blunder 😅
