### ISSUE TITLE
lint-staged now supports config CLI flag

### ISSUE THREAD

**Issue by AndersDJohnson** [kentcdodds/kcd-scripts#24]
We no longer need the `lint-staged` config require cache hack (https://github.com/kentcdodds/kcd-scripts/blob/1fa8622/src/scripts/precommit/lint-staged.js#L16-L20) since it supports `--config` CLI flag since https://github.com/okonet/lint-staged/releases/tag/v4.3.0.

**Comment by kentcdodds** [comment]
Oh that's wonderful! I did _not_ like the current "solution" as it's very hacky. I'd love a PR to add the `--config` flag support instead 👌

**Comment by macklinu** [comment]
I opened #31 to address this.

**Comment by kentcdodds** [comment]
Thanks @macklinu!
