### ISSUE TITLE
Is it worth adding *.ts and *tsx to jest.config.js

### ISSUE THREAD

**Issue by mateuscb** [kentcdodds/kcd-scripts#25]
- `kcd-scripts` version: 0.27.2
- `node` version: 9.3.0
- `yarn` version: 1.3.2

Relevant code or config

```javascript
  collectCoverageFrom: ['src/**/*.js'],
  testMatch: ['**/__tests__/**/*.js'],
  testPathIgnorePatterns: [...ignores],
  coveragePathIgnorePatterns: [...ignores, 'src/(umd|cjs|esm)-entry.js$'],
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$'],
```

 

Problem description: This isn't a huge problem since the benefit of `kcd-scripts` is the ability to overwrite options. But, given the high number of typescript, it would be nice to not have to overwrite the same options every time.

Suggested solution: Before creating a PR, I wanted to pose the question to see what others thought. Is addin `*.ts` and `*.jsx` to jest.config.js a worthy thought?

**Comment by kentcdodds** [comment]
Hi @mateuscb!

I prefer flow, but I can understand why others might want to have improved typescript support. I definitely do not plan on including typescript specific scripts etc., but for simple things like this where it doesn't make the codebase much more complex, I'm ok to accept a PR for it.

Thanks :)

**Comment by mateuscb** [comment]
Hi @kentcdodds!

Cool, OK I'll work on a PR for that. Thanks!
