### ISSUE TITLE
eslint error - Cannot find module '@ljharb/eslint-config'

### ISSUE THREAD

**Issue by InsightUI** [kentcdodds/kcd-scripts#41]
* `kcd-scripts` version: 0.37.0
* `node` version: 9.11.1
* `npm` version: 5.3.0

What you did:
Create fresh copy of create-react-app
install kcd-scripts as dev dependency
Add lint script to `package.json`
- `"lint": "kcd-scripts lint"`

What happened:
```cli
Cannot find module '@ljharb/eslint-config'
Referenced from: C:\Node\test-project\node_modules\array-includes\.eslintrc
Error: Cannot find module '@ljharb/eslint-config'
Referenced from: C:\Node\test-project\node_modules\array-includes\.eslintrc
    at ModuleResolver.resolve (C:\Node\test-project\node_modules\kcd-scripts\node_modules\eslint\lib\util\module-resolve
r.js:74:19)
```

Reproduction repository:

I created a fresh copy of react-react-app
`npx create-react-app test-project`
No need for a production repo

Problem description:
I don't see `@ljharb/eslint-config` referenced in the internal eslint config for kcd-scripts so I don't know where this error is coming from. I can only assume it has something to do with array-includes package but I'm not 100%

Suggested solution:
I do not have a suggested solution at this time.

**Comment by InsightUI** [comment]
No problem. Thanks for the quick reply.

**Comment by egemon** [comment]
If someone got here as well as me - it also may happen if u accidentally added files from node_modules to git index and trying to commit using husky+lint-staged
