### ISSUE TITLE
Project starter based on kcd-scripts?

### ISSUE THREAD

**Issue by stereobooster** [kentcdodds/kcd-scripts#44]
* `kcd-scripts` version: N/A
* `node` version: N/A
* `npm` (or `yarn`) version: N/A

Relevant code or config N/A

What you did: N/A

What happened: N/A

Reproduction repository: N/A

Problem description: 

How to bootstrap fresh project with `kcd-scripts`? For `create-react-app` I do 

```sh
create-react-app project-name
```

Suggested solution: 

Provide command to bootstrap fresh project or empty github repo which can be used as reference.

**Comment by kentcdodds** [comment]
Hey @stereobooster!

This is what I do today:

```
npx -p yo -p generator-kcd-oss -c 'yo kcd-oss'
```

I have that aliased to `kcd-oss`. It's working for me pretty well. [My yeoman generator](https://github.com/kentcdodds/generator-kcd-oss) is pretty good. I think a `create-kcd-oss` thing would be cool, but I'm probably not going to find time to work on that any time soon.

**Comment by stereobooster** [comment]
Thank you. yeoman is good enough for me
