### ISSUE TITLE
Could not parse lint-staged config.

### ISSUE THREAD

**Issue by stereobooster** [kentcdodds/kcd-scripts#45]
* `kcd-scripts` version:  "0.38.1"
* `node` version: v8.6.0
* `npm` (or `yarn`) version: 5.5.1

Relevant code or config

What you did:

```
git commit -m "..."
```

What happened:

```
husky > npm run -s precommit (node v8.6.0)

Could not parse lint-staged config.

Error: Cannot find module './node_modules/kcd-scripts/dist/config/lintstagedrc.js'

Please make sure you have created it correctly.
See https://github.com/okonet/lint-staged#configuration.

husky > pre-commit hook failed (add --no-verify to bypass)

...
ls -la ./node_modules/kcd-scripts/dist/config/lintstaged.config.js
-rw-r--r--  1 xxx  zzz  707 May 21 12:05 ./node_modules/kcd-scripts/dist/config/lintstaged.config.js
```

Reproduction repository:

https://github.com/stereobooster/react-precious-image

Problem description:

`lint-staged` can not resolve path to the config properly

Suggested solution:

provide full path to the config (starting from the root)

**Comment by kentcdodds** [comment]
Weird. So from the look of it, you have a `lintstaged.config.js` file in `kcd-scripts/dist/config`? I'm not sure how that's possible considering it's actually [`lintstagedrc.js`](https://github.com/kentcdodds/kcd-scripts/blob/master/src/config/lintstagedrc.js) 🤔

**Comment by stereobooster** [comment]
Sorry for confusing you. I created `lintstaged.config.js` manually. I have both files `lintstagedrc.js` and `lintstaged.config.js`.

```
ls -la ./node_modules/kcd-scripts/dist/config/lintstagedrc.js
-rw-r--r--  1 xxx  zzz  707 May  4 05:16 ./node_modules/kcd-scripts/dist/config/lintstagedrc.js
```

Also I tried to remove repo, clone it again, run setup (`npm run setup -s`) and still get the error

**Comment by kentcdodds** [comment]
Weird. I just reproduced it locally. Any idea why I'm not seeing this on any of my projects?

I'm open to a PR that fixes this :+1:

**Comment by stereobooster** [comment]
Not sure why, but problem got fixed. I updated to the latest `kcd-scripts` also renamed repository. Will close for now
