### ISSUE TITLE
Pragma for Preact build is incorrect

### ISSUE THREAD

**Issue by donysukardi** [kentcdodds/kcd-scripts#50]
* `kcd-scripts` version: 0.39.1
* `node` version: 10.4.1
* `npm` (or `yarn`) version: yarn@1.7.0

Relevant code or config

```javascript
{
  plugins: [
   ... 
   isPreact
      ? [require.resolve('babel-plugin-transform-react-jsx'), {pragma: 'h'}]
      : null,
}
```

What you did: Build a preact bundle that includes JSX

What happened: JSX gets transformed to just `h` instead of `React.h` where *React* is Preact and h is undefined when trying to run the code with the built bundle.

Reproduction repository: https://github.com/donysukardi/kcd-scripts-preact-issue

Problem description: Pragma for Preact build is incorrect

Suggested solution: Update pragma to `'React.h'` instead of just `'h'`

**Comment by kentcdodds** [comment]
Hmmm... I don't think this is correct. I don't use the preact builds (in downshift for example) but I know some people do and they seem to have it working properly 🤔 Could you verify that it's broken for others and not just you?

**Comment by donysukardi** [comment]
I've put up a reproduction repo here https://github.com/donysukardi/kcd-scripts-preact-issue.

The only reason why it works for downshift (or some other libraries like dayzed or kalendaryo) is that the library does not use any JSX.

Once you have jsx in one of the files, it will get transformed to `h` calls where `h` is undefined.

**Comment by kentcdodds** [comment]
Gotcha. That's enough for me! Thanks!

**Comment by donysukardi** [comment]
Resolved by https://github.com/kentcdodds/kcd-scripts/pull/51
