### ISSUE TITLE
Getting babelHelpers is not defined

### ISSUE THREAD

**Issue by donysukardi** [kentcdodds/kcd-scripts#52]
Changes in https://github.com/rollup/rollup-plugin-babel/commit/f8182c607b384d1c014b0e7cb70d4feb69073003 (v3.0.6) seem to be breaking the rollup build which was previously working fine.

Since this library is not committing lock file, `rollup-plugin-babel@^3.0.3` gets resolved to `3.0.6`.

I am getting `babelHelpers is not defined` error when trying to run the build artefact.

![image](https://user-images.githubusercontent.com/410792/42136328-b2c2d31e-7d8b-11e8-9998-f9faced79a18.png)

It seems to be working fine after I remove `"babel-plugin-external-helpers"` plugin from .babelrc though.

Reference: https://github.com/rollup/rollup-plugin-babel/issues/228

**Comment by Andarist** [comment]
This can be closed now - I've reverted the change so should be fixed in rollup-plugin-babel@3.0.7

**Comment by donysukardi** [comment]
It's working as expected again with rollup-plugin-babel@3.0.7
