### ISSUE TITLE
Jest environment.teardown error with CRA (conflicting versions)

### ISSUE THREAD

**Issue by v1adko** [kentcdodds/kcd-scripts#59]
*Note*: 

This is not an issue per se, but more of a heads-up/unofficial docs for people who encounter the same problem. However this can spark some discussions on how to manage versions of the external (app) and internal (toolbox) dependencies.

*Env*:
- `kcd-scripts` ^0.42.1:
- `node`: 8.11.3
- `yarn` 1.9.4

*What you did*:

Use default pre-commit on CRA based repo.

*What happened*:

`
  TypeError: environment.teardown is not a function
`

![screen shot 2018-08-17 at 12 15 00 am](https://user-images.githubusercontent.com/11582927/44235558-a2a87600-a1b2-11e8-84dd-763261b3a4f6.png)

*Problem description:*

The issue is realated to the fact that CRA does not allow conflicting Jest versions.

Related issues for some background: [jest#6393](https://github.com/facebook/jest/issues/6393), [jest#5119](https://github.com/facebook/jest/issues/5119#issuecomment-356120965)

*Suggested solution:*

Add `lint-staged` entry in your package.json, ultimately overwriting actions on pre-commit hook, something along these lines
```json
  "lint-staged": {
    "*.js": [
      "yarn format",
      "yarn lint",
      "git add"
    ]
  },
```

**Comment by kentcdodds** [comment]
Yeah, not much we can do about this I'm afraid. Thanks for making it googleable though!
