### ISSUE TITLE
Scoped package name is resulting into weird path in dist/

### ISSUE THREAD

**Issue by halfzebra** [kentcdodds/kcd-scripts#69]
Hi @kentcdodds!

Thanks for the scripts, very cool project. I've been looking for something like this for a few months and how happy I was to find this. 🙂 

I have stumbled upon a little issue. The scoped packages are getting unconventional build artifacts.

`@namespace/package-name` is getting a file structure that reflects the name `/dist/@namespace/package-name.umd.js`

What do you think about converting `@namespace/package-name` -> `namespace-package-name` or maybe even dropping the `namespace` if it is present?

Please feel free to close this if you don't find it relevant or necessary. I'm willing to send a quick PR if this makes sense.

**Comment by kentcdodds** [comment]
Hi @halfzebra,

That's actually not a problem. You just update your `main` and `module` to point to the right file.

In any case, I'm not taking feature requests on this project. If you want something to work differently then you can fork it :)

**Comment by halfzebra** [comment]
Thanks for the reply! It seems like it's gonna work just fine, so I'll roll with it as it is. 🙌
