### ISSUE TITLE
Allow to debug unit tests, e.g. Visual Studio Code

### ISSUE THREAD

**Issue by weyert** [kentcdodds/kcd-scripts#78]
- `kcd-scripts` version: 0.48.0
- `node` version: v11.3.0
- `npm` (or `yarn`) version: 6.4.1

I would like to be able to debug unit tests and indirectly my library code from Visual Studio Code only currently I am not able to get it working easily. I think it might be related to the use of cross-spawn. The main problem is that Visual Studio passed `--inspect-brk=33548` argument to the node while `run-script` expects the script name. E.g. `kcd-scripts --inspect-brk=33548 test`

How are you currently debugging the code base? E.g. downshift?

**Comment by kentcdodds** [comment]
> How are you currently debugging the code base? 

console.log 😅

**Comment by weyert** [comment]
Ah okay, I wanted to use the node debugger but haven't got it working yet

**Comment by weyert** [comment]
A PR has been merged which allows passing `--inspect-brk` and similar node arguments to `kcd-scripts`. Closing this ticket

**Comment by kiranjd** [comment]
This VS Code configuration worked for me:
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Debug CRA Tests",
        "type": "node",
        "request": "launch",
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/kcd-scripts",
        "args": ["test", "--runInBand", "--no-cache", "render.js"],
        "cwd": "${workspaceRoot}",
        "protocol": "inspector",
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "env": { "CI": "true" },
        "disableOptimisticBPs": true
      }
    ]
  }
  ```
