### ISSUE TITLE
Add A Helpful Error for Node Versions less than 8.x

### ISSUE THREAD

**Issue by ijones16** [kentcdodds/kcd-scripts#9]
- `kcd-scripts` version: v0.25.1
- `node` version: v7.4
- `npm` (or `yarn`) version: v5.4.2

Relevant code or config

``` bash
npm run build
```

What you did:
Ran this command on Node v7

What happened:
Got an output that did not indicate Node v8 was required.
```
> kcd-scripts@0.0.0-semantically-released build /Users/ianjones/Desktop/egghead-dev/kcd-scripts
> node src build

/Users/ianjones/Desktop/egghead-dev/kcd-scripts/src/index.js:18
    )
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Problem description:
This seems to cause issues with projects that depend on kcd-scripts. Here is a reference: 
https://github.com/kentcdodds/generator-kcd-oss/issues/6

It is a more straight-forward error when you experience it in the context of this project. It is likely confusing for someone who would run into this using generator-kdc-oss.

Suggested solution:
Print an error telling the user that Node v8 is required.

**Comment by kentcdodds** [comment]
I can probably do that. Thanks for the issue! :+1:
