### ISSUE TITLE
Question: working with various eslint config wrinkles

### ISSUE THREAD

**Issue by jrnail23** [kentcdodds/kcd-scripts#90]
Hi @kentcdodds, I apologize if this isn't the best place to ask this question, but I'm working on a custom scripts toolkit of my own, borrowing heavily from `kcd-scripts`, so I thought this might help others who were similarly inspired by this project.

I've started off by re-implementing your linting approach almost directly, and I'm harvesting eslint config from the existing projects I'm supporting, but I'd like to pick your brain about handling a couple various eslintrc wrinkles in my toolkit's `config/eslintrc.js`.

First, how would you deal with exporting things like "recommended" configs from plugins?  I see you use `require.resolve` in your implementation (which, I assume is done to ensure you're exporting config from the toolkit's `node_modules` instead of the consuming project's `node_modules`), but I'm not quite sure how that might map to usages like this:
```js
extends: [
  "eslint:recommended",
  "plugin:flowtype/recommended",
  "plugin:react/recommended",
  "plugin:import/errors"
],
```

Also, how would you recommend sharing config that's scattered across several `.eslintrc` files?  For example, In a `react` web app with an `express` backend, I've got config files with different plugins/rules/etc. for my `server` folder (settings for pure non-transpiled node stuff), and my `client` folder (react, flow, babel transpiled stuff), and also `test` folders (things like `jest` or `cypress` settings, also inheriting/extending the settings for the source code they target).

Thanks in advance!

**Comment by kentcdodds** [comment]
I'd do it like this:

```javascript
extends: [
  require.resolve('eslint/conf/recommended'),
  require.resolve('eslint-plugin-flowtype/dist/configs/recommended.json'),
  // etc...
]
```

Good luck!

**Comment by jrnail23** [comment]
@kentcdodds, thanks for the quick reply!
Any thoughts on that second question (pulling those multiple config files into my toolkit)?

**Comment by kentcdodds** [comment]
You _could_ use the `overrides` feature of eslint, but that doesn't allow for `extends` which is super annoying. But I've done that before.

You could also just require that people add an `.eslintrc` which does: `extends: "your-module/eslint-server"` for example.

**Comment by jrnail23** [comment]
yeah, adding the extends sounds like it might be the most feasible way to go.
Thanks again!
